### ISSUE TITLE
Make text mining work

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#108]
The frontend API prototype for text mining is finished, we need to hook the fronted up with the backend - Fenominal.

### Definition of done

- [x] - Fenominal has a stable release
- [x] - create an backend endpoint for text IO
- [x] - implement the backend

**Comment by belkassaby** [comment]
[f45445f](https://github.com/TheJacksonLaboratory/PhenopacketLab/pull/103/commits/f45445fcd5e69773ed129aeaa2a0be1c12bc8d11) added the backend endpoint for text IO
