### ISSUE TITLE
Add info box with description and id on searchable ontology terms

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#112]
## Definition of done
when hovering a particular term from an ontology (on a dropdown or elsewhere) we should display a description dialog/tooltip with the corresponding id and description of the said term. The id could also link to the external page for the given term.

**Comment by belkassaby** [comment]
See commit [2826f5](https://github.com/TheJacksonLaboratory/PhenopacketLab/pull/133/commits/2826f5aca06418f8f7935ae67c0da21497aed045)

**Comment by desais-jax** [comment]
@belkassaby I see the ontology details only in disease Ontology drop down. Is there any other place where I should be viewing the tooltip or dialog?

**Comment by desais-jax** [comment]
@belkassaby :looks good now. But I see the ID but  i see prefix from CL and GO and UBERON. Is that correct. I thought we were only iimporting from HPO site. Are we integrating with some other application too inorder to get the ontologies?

**Comment by belkassaby** [comment]
@belkassaby yes, the disease ontology for instance comes from an ingested file which is built from the mondo ontology (and which has terms from different ontologies, orpha, go etc). We get the phenotypic features from the HPO ontology.
