### ISSUE TITLE
Allow / disallow phenotypic feature ID renaming 

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#116]
When adding a custom new phenotypic feature (new name ) it is not possible to edit its id/label.

**Comment by pnrobinson** [comment]
Not sure I understand this issue, but we do not want people to be able to manually enter id and name fields because they could potentially change them to be inconsistent with each other (or otherwise invalid). If you want to enter an entry, you should delete the current entry and try again.?

**Comment by BethSundberg** [comment]
This is fixed
