### ISSUE TITLE
CHeck modifiers selection in phenotypic feature saving

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#117]
In the Create Phenopacket section, I tried to edit a term to add some detailed information. When I checked miliary, it also checks localized (and vice versa). I looked in the HPO terms and there is no association between the	se that I can see. 
To reproduce: go to create phenopacket
Select Feature search
Enter “alopecia”
Select patchy alopecia
Click on patchy alopecia so it shows up on the right side of the page in the phenotypic feature details column
Click on edit more details
Look under modifiers, In the hierarchy, scroll down to position, open it
Open spatial pattern
Click on miliary
NOTE that localized is also checked, but only miliary shows up in the modifiers “box”.
If you check localized first, miliary is also checked but only localized shows up in the modifiers box.
Are these two mutually exclusive? I cannot get both terms to show up in the modifiers box.

**Comment by belkassaby** [comment]
@BethSundberg after testing, it seems it is a bug that comes from the data that is served by the fakebackend which is corrupted: localized should have children whereas here is does not. It works with the application being served data by the backend. I will update the data served by the fakebackend. Fixed in [927d1fcd](927d1fcdfbd9873592e4295d423f425d7365f5b1)

**Comment by BethSundberg** [comment]
@belkassaby This specific issue has been fixed. I am marking it as done. If I find any other similar issues, I will let you know.
