### ISSUE TITLE
Fix saving bug

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#118]
## Steps to recreate
-upload a correct phenopacket json file (covid.json in the respapi example)
-save it to json
-re-upload the saved json
*the measurement includes measurementValue parameter when it should be 'value'.
*in the disease object and other places (phenopacket object too) empty lists are still saved in the JSON when they shouldn't be there.

**Comment by BethSundberg** [comment]
@belkassaby I don't know enough about how the json should look. Which is correct:

Choice number 1:

"measurements": [{
    "assay": {
      "id": "LOINC:26474-7",
      "label": "Lymphocytes [#/volume] in Blood"
    },
    "value": {
      "quantity": {
        "unit": {
          "id": "NCIT:C67245",
          "label": "Thousand Cells"
        },
        "value": 1.4
      }
    },
    "timeObserved": {
      "interval": {
        "start": "2019-09-01T00:00:00Z",
        "end": "2020-03-01T00:00:00Z"
      }
    }
  },

Choice number 2:

"measurements": [
      {
         "assay": {
            "id": "LOINC:26474-7",
            "label": "Lymphocytes [#/volume] in Blood"
         },
         "measurementValue": {
            "value": {
               "unit": {
                  "id": "NCIT:C67245",
                  "label": "Thousand Cells"
               },
               "value": 1.4
            }
         },
         "timeObserved": {
            "interval": {
               "start": "2019-09-01T00:00:00Z",
               "end": "2020-03-01T00:00:00Z"
            }
         }
      },

**Comment by belkassaby** [comment]
Hi @BethSundberg #1 is the correct one. the 2 i suspect was created when saving it with the app right?

**Comment by BethSundberg** [comment]
@belkassaby  Yes, number 2 was created when I saved number 1. This indicates that this bug is not yet fixed, unless you have it fixed on a different branch. I am using the "use_api_endpoint_to_populate_ontologies/frontend" branch.

**Comment by BethSundberg** [comment]
Saving is now working.
