### ISSUE TITLE
PhenopacketLab: packet I created missing an id

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#119]
I created a pretty simple phenopacket. I saved the json, then tried to open it.

Error: Phenopacket file is missing 'id' field in 'subject' object.

![Image](https://user-images.githubusercontent.com/11503959/215195267-dfb817ae-20b1-43da-b0fe-04d391a84d8f.png)

Here is the beginning of the json:

{
   "id": "BethTest1",
   "subject": {
      "id": "",
      "alternateIds": [],
      "vitalStatus": {
         "status": "ALIVE"
      },
      "timeAtLastEncounter": {
         "age": {
            "iso8601duration": "P12Y11M10D"
         }
      },
      "sex": "FEMALE",
      "karyotypicSex": "XX"
   },

**Comment by belkassaby** [comment]
The id field in the subject object is mandatory, that is the reason why the upload is failing.

**Comment by BethSundberg** [comment]
Fixed
