### ISSUE TITLE
Add CD to frontend and backend

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#125]
## Definition of done
Implement Continuous deployment for frontend and backend to GCP:
*frontend deployment should include the creation of the docker image and pushing it (with release versions) to GCP (artifact registry) and deleting and applying the new application in the given namespace
*backend deployment should include running the ingest, building the restapi jar, creating the docker image, pushing it to GCP to the artifact registry and deleting and applying the new application in the given Kubernetes namespace

**Comment by iimpulse** [comment]
https://github.com/TheJacksonLaboratory/hpo-web/tree/feature/gcp/.github/workflows

**Comment by belkassaby** [comment]
Waiting for RIT tickets to be solved (RITM0201342, RITM0202162 and RITM0201342)
