### ISSUE TITLE
When a phenopacket is deleted from the list, remove the ID from the map

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#128]
To reproduce:
Create a phenopacket
Save the json
delete the phenopacket from the list on screen
upload the phenopacket you previously saved
Bug: unable to open unless you exit the session first

**Comment by belkassaby** [comment]
Tested on latest version of dev: fixed.

**Comment by BethSundberg** [comment]
Confirmed it is fixed.
