### ISSUE TITLE
Unable to clear onset and resolution from phenotypic feature in the stepper

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#143]
Removing onset or resolution (setting to `null`) does not work once either one is set.

For instance, after selecting *Age*, the `P5Y` is correctly shown in the *Added phenotypic features* table:
![image](https://user-images.githubusercontent.com/12170955/223739756-e6cb4c5a-3cfb-4656-acd1-908cca64a571.png)

The cross within the onset class selector (Age, Age range, etc.) should clear the onset for the selected phenotypic feature. After clicking on the cross icon, indeed, the onset is cleared. 
![image](https://user-images.githubusercontent.com/12170955/223740273-fb25ac30-278b-4c63-a25e-738d856d4c99.png)

However, the change is not in sync with the *Added phenotypic features* table, and seemingly also with the underlying data model. The *Onset* table column is not cleared and the *Phenotypic feature details* | *Onset* field is reset to *Age* after selecting the term again.
![image](https://user-images.githubusercontent.com/12170955/223741217-f1cb68c0-aba7-4c7f-830b-11237f21f461.png)

**Comment by ielis** [comment]
The same issue seems to be present in *Stepper* | *Disease* | *Disease details*. Onset and resolution cannot be cleared once set.

**Comment by belkassaby** [comment]
This should be fixed in the current branch im working on. I'll let you know once I have deployed it.

**Comment by BethSundberg** [comment]
@belkassaby  The onset is clearing. However, I have a question about the resolution. It is clearing fine in the detail section, but sometimes it gives me "undefined" under the resolution heading in the top. It also is not clearing or changing that resolution heading.



![Image](https://user-images.githubusercontent.com/11503959/226381999-38cc8fba-82df-49f9-9396-dcd665b31511.png)

**Comment by belkassaby** [comment]
in the SQA instance, when deleting an onset, and then selecting another onset (age, agerange or gestationalAge) although the value is changed it is not display on the row of the table.
