### ISSUE TITLE
Unable to clear severity in Stepper | Phenotypic features | Phenotypic features details

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#144]
Once *Severity* of a phenotypic feature is set in the *Phenotypic Feature details* pane, it is not possible to unset it.

I would like to propose using the same UI element which we use for selecting Onset/Resolution class (*Age*, *Age range*, etc.) which has the cross icon to allow unset the selection:
![image](https://user-images.githubusercontent.com/12170955/223742366-95421349-1e53-493a-8df9-c7332a0f7e2d.png)

**Comment by BethSundberg** [comment]
@belkassaby  Has this been merged into http://35.227.26.28/phenopackets ? I don't find an "x" for severity.

**Comment by BethSundberg** [comment]
This is now fixed.
