### ISSUE TITLE
First screen distinction between "rare disease" vs "all available steps" is not understandable

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/PhenopacketLab#146]
The difference between these "rare disease" vs "all available steps" options needs different language or explanation. Even going through it the steps look the same. I'm on http://35.229.81.196/creator/rare/phenotypic-features

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/3658863/225132308-3e07bcfc-9e24-419f-b444-d6c0fef07fe7.png">

**Comment by jmcmurry** [comment]
<img width="1427" alt="Screenshot 2023-03-14 at 1 48 33 PM" src="https://user-images.githubusercontent.com/3658863/225132762-06c9a27c-c64e-44d3-8fd2-4500ca3d1fbc.png">

<img width="1445" alt="Screenshot 2023-03-14 at 1 48 47 PM" src="https://user-images.githubusercontent.com/3658863/225132794-ac0dbdc0-e07f-439e-a0a2-691f098226f7.png">

Now I see that there are different steps available. I don't think this is worth explaining this distinction from the outset as it is hard to grok.

Instead considering just prompting the user and allow them to skip steps as desired. I could be missing something?

**Comment by belkassaby** [comment]
Should we just remove the all available profile for now as it's not really available (as in not implemented yet). Then for now the user will be redirected to the individual step after clicking on "create a new phenopacket". We would show only the implemented steps. @pnrobinson  @ielis  what do you think?

**Comment by jmcmurry** [comment]
So, just to clarify my suggestion ... Even when the additional modalities DO become available, it is very difficult (and not necessary) to responsibly convey this before the users even begin. I don't see a compelling reason not to just dump users directly to http://35.229.81.196/creator/all/individual since if they've come to the site it is to create a phenopacket and that can't be done without at least phenotypes

Instead I would strongly recommend getting through steps 1 and 2 first and then have the user step through each optional modality and just click "next" if they wish to bypass it. This stepwise approach has the following advantages

- it is more in step with prevailing UX practice (think airlines and whether you want to select your seats, add bags etc.)
- it enables us to provide some context about what it is we even mean by each modality (Context for the user is especially important for more fuzzy concepts like 'measurement' or even 'medical action' that may not be universally understood in the same way)
- it is technically easier to execute because we can roll out one modality at a time without rethinking the whole interface. 

I welcome your thoughts on this :)

**Comment by BethSundberg** [comment]
Changed as described.
