### ISSUE TITLE
Remove severity from modifiers box

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/PhenopacketLab#149]
It is confusing that severity is duplicated above and below. Unless I'm missing something, it would be better to leave it out of the bottom?

<img width="300" alt="Screenshot 2023-03-14 at 2 53 46 PM" src="https://user-images.githubusercontent.com/3658863/225148918-1144d2ad-8871-450c-bc7c-67bbff2ab54b.png">

**Comment by pnrobinson** [comment]
Agree, severity should be left out of the bottom list!

**Comment by belkassaby** [comment]
The commit above also removes laterality as well as severity out of the modifier tree.

**Comment by BethSundberg** [comment]
Tested and looks good
