### ISSUE TITLE
Creator field type not specified

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/PhenopacketLab#153]
It would be good if we could specify what kind of field is expected for created by and submitted by.
Ideally we could support both name and orcid.

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/3658863/225377898-60033b4e-4527-4567-8fcd-b9d628bcdbfc.png">

**Comment by belkassaby** [comment]
Yes that's true. For now it's only a simple string input field. If an Orcid we could have a regex formatting input field (similar to the telephone number input fields).

**Comment by jmcmurry** [comment]
I strongly recommend adding a separate ORCiD field at earliest opportunity
However, for privacy reasons it may sometimes be appropriate for someone to author a phenopacket anonymously, so maybe preface the created by and submitted by with "Author as myself, Author anonymously" or such.
In meantime you'll get a mixed bag of drek if you don't at least specify whether you're looking for name, email, github handle, or ham radio call signal ;)

**Comment by pnrobinson** [comment]
I do not think we need to cater to people who want to remain anonymous, we should probably just make ORCID absolutely required!

**Comment by belkassaby** [comment]
Hi Peter, Hi Julie,
what do you think of this UI for the ORCid field? Here I am saving the orcid string if any in the createdBy/submittedBy property of the metadata object of the phenopacket.
![Screen Shot 2023-03-16 at 9 45 55 AM](https://user-images.githubusercontent.com/1378819/225637336-a1d452aa-608d-43b7-bbcf-dee5ee3affbc.png)

**Comment by pnrobinson** [comment]
seems fine for now, but we need to explain that we want an ORCID id. Many sites allow you to login to the ORCID webiste and retrieve your information as JSON, including the ORCID id, using this -- https://info.orcid.org/documentation/api-tutorials/api-tutorial-get-and-authenticated-orcid-id/

**Comment by pnrobinson** [comment]
Our first use case for the app is for authors to create phenopackets, and so here we definitely want to require ORCID. We could set up another profile in the future for other use cases?

**Comment by jmcmurry** [comment]
Yup; one step at a time

**Comment by BethSundberg** [comment]
Use of orchid looks good, I can also be anonymous. It would be nice to be able to change this later after it is finished?
