### ISSUE TITLE
Remove or explain the side panel

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/PhenopacketLab#154]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/3658863/225508534-00198b1a-3a5d-4984-baa7-4a79b2eb3e87.png">

When already in the middle of creating a phenopacket it is confusing to have "add phenopacket" as a visible option. I recommend removing this panel and instead prompting the user at the end of phenopacket creation if they'd like to add another. Am I missing something here @pnrobinson ?

I like the progress bar at the top to orient users within the workflow so I don't think we need the left sidebar for that. The exception would be if we build out MORE steps that no longer fit on a horizontal screen. Not sure how this renders on mobile?

**Comment by belkassaby** [comment]
@iimpulse is working on adding the ability to make the menu hidden if needed. See #135

**Comment by BethSundberg** [comment]
Side panel is gone
