### ISSUE TITLE
syntax of "age of clinical encounter"

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/PhenopacketLab#156]
I find this phrasing a bit awkward and hard to understand. I think what is meant is "Age at last clinical encounter"; @pnrobinson please advise

<img width="250" alt="image" src="https://user-images.githubusercontent.com/3658863/225756863-c35accad-311f-4dcf-b500-048b9c668768.png">

**Comment by pnrobinson** [comment]
I agree -- we should show "Age at last clinical encounter" (the other labels are the names of fields in the phenopacket but we do not need to show this level of detail!)

**Comment by BethSundberg** [comment]
Tested and looks good.
