### ISSUE TITLE
Avoid multiple endpoint querying after each component is opened

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#178]
## Definition of done
Instead of querying ontology endpoints multiple times (everytime a component is loaded/reloaded) we should load all ontologies and relevant constants/terms/diseases/phenotypic features only once, when the single-page app is loaded the first time. The loading mechanism shall be implemented using angular services such as this: https://stackoverflow.com/questions/69537986/angular-multiple-reciepients-of-data-from-endpoint

**Comment by BethSundberg** [comment]
The ontology dropdowns are working nicely.
