### ISSUE TITLE
Test : Test Disease diagnoses step

### ISSUE THREAD

**Issue by desais-jax** [TheJacksonLaboratory/PhenopacketLab#182]
Test Scenario : 

1. Test Disease Search - search for various diseases 
2. Enter disease details 
3. Try to delete a disease that has been added 
4. Edit a phenopacket and try to edit Disease diagnosis details

**Comment by BethSundberg** [comment]
Adding a disease with lots of disease details is saved with no problems, json is created with no problems, also able to edit.
