### ISSUE TITLE
Test : Test Phenotypic Feature - Step2

### ISSUE THREAD

**Issue by desais-jax** [TheJacksonLaboratory/PhenopacketLab#183]
Test Scenario:

1. Phenotypic Features search - test search for ontologies 
2. Test text mining search 
3. Test Phenotypic feature details
4. Save the phenopacket and then edit things in step2. Try to add or edit and see if it retains changes.

**Comment by BethSundberg** [comment]
Regular phenotypic features search is working fine.

Changes are retained when editing.

There are some problems with the text mining, adding issues for those.
