### ISSUE TITLE
VitalStatus should not be required

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#186]
VitalStatus should be optional!

**Comment by belkassaby** [comment]
I made it required as the phenopacket-tools validator throws an error if it is missing from the phenopacket. What I could do for now is set the VitalStatus default value to UNKNOWN_Status so then phenopacket-tools validator will be ok?

**Comment by pnrobinson** [comment]
The element is not required!
Please always look at the schema - https://phenopacket-schema.readthedocs.io/en/master/individual.html
it is 0..1
If phenopackets-tools is throwing an error this is a bug in that software and needs to be reported there
@ielis

**Comment by belkassaby** [comment]
Yes, I knew it wasn't required in the schema; I should have told @ielis  about phenopacket-tools validation results throwing this error; instead I wanted to have something running for this demo I did, and pushed the changes to the dev environment. I will change the UI to not require VitalStatus and we'll have this fixed in phenopacket-tools.

**Comment by belkassaby** [comment]
So after further investigation, it appears it was all my fault: phenopacket-tools works fine, I was sending a phenopacket with a vitalStatus object, and phenopacket-tools was rightly telling me that status was missing in the vitalStatus object, which is correct. My mistake was to initialize the vitalStatus perperty when creating a new subject.

**Comment by ielis** [comment]
Oh, so it was something like:
```
vitalStatus: {}
```
instead of this?
```
vitalStatus: null
```

**Comment by belkassaby** [comment]
> Oh, so it was something like:
> 
> ```
> vitalStatus: {}
> ```
> 
> instead of this?
> 
> ```
> vitalStatus: null
> ```

yes: since vitalStatus was not undefined, phenopacket-tools was rightly so saying that the status property in it was null and required., When all that was needed was that vitalStatus should be set to null if not vitalStatus selected...

**Comment by BethSundberg** [comment]
Fixed
