### ISSUE TITLE
Variation Search

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#187]
This is not a search, it is a validation.

I think it should be called

"Enter variant data" (top level)

and the button that goes to variant validator should be called

"Validate variant"

We should also link out to the VariantValidator website -- good to give them credit!!

**Comment by belkassaby** [comment]
There is currently a link to the Variant Validator rest API, I'll put the link in bold so it is more obvious.  I will also change the "Variation search "to "validate variant" and the "search" button to "validate variant" as seen on the screenshot.
![Screen Shot 2023-06-09 at 2 40 02 PM](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/801a027e-7681-45e6-aff1-c4c3dbfa6229)

**Comment by BethSundberg** [comment]
Done
