### ISSUE TITLE
Please select interpretation status for genomic interpretation.

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#188]
This appears even though I have created an interpretation

**Comment by belkassaby** [comment]
I will set the default value of the interpretation status (property of genomic interpretation) to UNKNOWN as the UI doesnt not allow to create an interpretation with a genomic interpretation without its interpretation status. I did this as it is a required property if there is a genomic interpretation in an interpretation object.

**Comment by pnrobinson** [comment]
This makes sense. However, it would be good to have a warning if the user tries to submit the interpretation with UNKNOWN status because there are very few use cases where this would make sense (we expect the interpretation to be CAUSAL or CONTRIBUTORY in 99% of sensible use cases)

**Comment by BethSundberg** [comment]
The default value is set. However, there is no warning about unknown status. I am moving this back to In Progress

**Comment by BethSundberg** [comment]
Warning is now present
