### ISSUE TITLE
Add Upload and Save functionality

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#19]
We need to implement an upload and save feature. So that users can load a family/cohort dataset in json format and the corresponding dataset will populate the Phenopacket lab UI accordingly. 
The save feature is to enable users to save/edit their existing opened family/cohort in the UI.  See #21

**Comment by BethSundberg** [comment]
@belkassaby When you say "family/cohort dataset", can you provide a file?
