### ISSUE TITLE
Save state of "no private info" checkbox in individual step

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#192]
When selecting once the "I confirm that this ID is not a medical record number..." confirmation checkbox, we should keep in memory the fact that is has been checked instead of having to check it again.

**Comment by BethSundberg** [comment]
@belkassaby 
There are some problems with keeping the confirmation in memory. 

- If I start another new phenopacket, the confirmation checkbox is checked to begin with.
- If I uncheck the confirmation checkbox, I don't get an error from the individual section.
- If I edit the individual section (once the phenopacket has been submitted), I can change the confirmation checkbox to be unchecked but it is ignored and shows up as checked if I edit again.

**Comment by BethSundberg** [comment]
@belkassaby This is working much better now. It will not let me finish a new phenopacket unless the confirmation check box is checked, which is the goal.

I will note that when I look at an existing phenopacket in edit mode, I can uncheck the confirmation check box and it does not care. But at that point the user has already previously done the confirmation. 

However, if they change the User ID when editing, perhaps you need to make sure that the confirmation check box is still checked? That would be the one way they might later add personal identifying information to the phenopacket.
