### ISSUE TITLE
Phenotypic Feature onset value is not displayed

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#194]
Here is an example of a phenotypic feature set that I created.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/2f329823-5ec8-430e-be2e-b94c236f2407)

The onset column is not displayed even though I put in different onset ages for the three rows for "cough". The values are saved in the json. 

Either display the onset or remove the column header.

**Comment by belkassaby** [comment]
This should be fixed in the current dev branch
