### ISSUE TITLE
Edited a disease to add onset, but the value does not show up

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#195]
Scenario:

Add a disease to an existing phenopacket.

Check that it is now shown properly.

edit the disease to add an onset of age: 41 years

click OK

Open the display of the disease using the accordion.

No onset is displayed either in the top line or within the details. However, the onset value is added to the json.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/f803bbfd-b160-43cc-acdc-bed66ccc55ab)

**Comment by belkassaby** [comment]
Fixed in dev branch

**Comment by BethSundberg** [comment]
Fixed
