### ISSUE TITLE
No way to add a "type" to a disease

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#196]
The display of the disease details includes an "Type" but there does not seem to be a way to add this. Should that be removed?

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/7f3af50c-ff25-4bac-870f-ef4249696b65)

**Comment by BethSundberg** [comment]
@pnrobinson So where on the display should the word "Type" be placed?

**Comment by belkassaby** [comment]
Yes I should remove the remove the type label as it is already at the top of the detail UI

**Comment by BethSundberg** [comment]
Fixed
