### ISSUE TITLE
For a deceased case, unable to add disease stage etc until editing

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#197]
Scenario

Create a phenopacket with a gestational age that is deceased before birth.

in the disease section, add the disease with a gestational age onset and resolution that is before birth

Here is a screen shot of the disease section. It is not possible to add disease stage, clinical findings or laterality at this point. There is no option for these.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/34356765-501b-4f61-a9e7-dff4f1eba9b9)

After completing the phenopacket, look at it on the display. Here edit more details is available and can be added. Is this a correct flow?

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/05ae53a7-2ebf-4203-b7c1-ce2d19104840)

**Comment by belkassaby** [comment]
Yes, Peter asked to make the creation of a rare-disease related phenopacket simpler, and to remove the edit UIs for disease stages, clinical findings and laterality. Then when the phenopacket is created, if the user wants to, they can edit the full phenopacket properties.

**Comment by BethSundberg** [comment]
OK, then this is working as Peter expects.
