### ISSUE TITLE
Save interpretation not working

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#198]
I have added an interpretation to an existing phenopacket and clicked "Save interpretation" and nothing happens. The modal does not close and no errors are listed to be corrected. Here are some screen shots. I have also tried editing an existing interpretation, one created before finalizing the phenopacket. In this scenario, the "save interpretation" button also does not work. So the problem looks to be with the edit interpretation modal.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/0c65a5fb-680d-4455-9776-edeb819ed38c)

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/93050a36-b405-483a-a8b2-055ac2dc2364)

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/be44ab01-c923-4866-922f-7f38093d1fd0)

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/afc3f138-9441-493c-bc90-a9da3292e4bf)

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/2174c1f8-a3f2-4ed3-94c0-52d065be71ca)

**Comment by belkassaby** [comment]
This seems to be fixed on the dev branch

**Comment by BethSundberg** [comment]
The flow for interpretations is much better. The modal is closing and it appears that the interpretation is saved. I can find it in the json. However, the main screen never lists interpretations in the accordion. I will put in a new bug for that. Closing this bug.
