### ISSUE TITLE
Unable to add a second interpretation

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#200]
The UI allows me to attempt to add more than one interpretation. But when I tried to do that I get an error.

Here is the screen, showing the second interpretation row I want to add.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/3236797e-aa4e-4d2f-88e3-1c69408be6bf)

When I click on "save interpretation" I get this error. The message implies that I need to start a whole new interpretation that has a different ID.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/b95471cc-b99c-40ee-a064-c3689fbb6c6d)

After trying this several times I think the problem is that you MUST NOT click on Save Interpretation until you are completely done filling in everything. I was trying to put in some values, save, then add more values to the existing interpretation. In the example above it did save the second interpretation row, but without the rest of the values I was trying to add.

I also was able to edit the interpretation number and then save a second interpretation.

The interface is confusing!

I should be able to add several interpretations to one diagnosis, which has the same interpretation ID? Then go on to add a second interpretation ID for a different diagnosis?

**Comment by belkassaby** [comment]
Yes, i agree the UI/UX could be greatly improved. It's stopping you from creating a new interpretation as the form still has the previous interpretation ID filled in and doesn't allow you to create an new interpretation with the same id as one of the existing interpretations.

**Comment by BethSundberg** [comment]
@belkassaby So, I think what I want to be able to do is to add rows to an interpretation that contain different genomic information. This should not be called "Add interpretation", perhaps some other wording can be used.

**Comment by belkassaby** [comment]
I'm using the schema names used in the phenopacket schema: an interpretation in the phenopacket schema is an object that can contain 0-* genomic interpretations. the phenopacket object can have 0-* interpretations. the "save interpretation" button at the end is to add/save the overall interpretation to the list of interpretations in the phenopacket. I will put the "add genomic interpretation button in the header of the genomic interpretation table so it is clearer

**Comment by BethSundberg** [comment]
Well the button helps, but I still make the same error. I added a different issue for this.
