### ISSUE TITLE
Validation message hard to understand

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#202]
I tried to add a new phenopacket where I entered only the information for the "Individual" section. I get this validation message. After pondering for awhile perhaps it means I must enter at least something on one of the other sections? Can the message be clearer? I also note that it looks like I can click the "complete" button. Is that okay, i.e. the message is only a warning? 

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/d71b8c9b-f6f7-416d-a943-f4d0b26cf191)

I tried using the "complete" button and now I have my new phenopacket listed. I saved the json. Then I tried clicking the yellow "validation" button. That brings up the same message as shown above. 

When I clicked on OK, my phenopacket has vanished, it is no longer listed. --- update, I can't duplicate this, my best guess is I accidentally managed to click on the delete icon.

I tried uploading the json and nothing happens, it is not uploaded. This I can duplicate, the json must be malformed since it had the error shown above. I am able to upload the json for other phenopackets. Should the user be able to save the json for a phenopacket with warnings?

**Comment by belkassaby** [comment]
could you upload on this issue the json of the created phenopacket?

**Comment by BethSundberg** [comment]
@belkassaby This is what won't upload:
{
   "id": "Beth test 1 on Wed",
   "subject": {
      "id": "sqa testing",
      "alternateIds": [],
      "sex": "FEMALE",
      "karyotypicSex": "XX",
      "vitalStatus": {
         "status": "ALIVE"
      }
   },
   "phenotypicFeatures": [],
   "measurements": [],
   "biosamples": [],
   "interpretations": [],
   "diseases": [],
   "medicalActions": [],
   "files": [],
   "metaData": {
      "createdBy": "Anonymous undefined",
      "submittedBy": "Anonymous undefined",
      "resources": [],
      "created": "2023-06-14T13:39:42.714Z",
      "externalReferences": [],
      "phenopacketSchemaVersion": "2.0"
   }
}

**Comment by belkassaby** [comment]
Weird... seems to work for me : the upload of that json: 
![Screen Shot 2023-06-14 at 12 03 04 PM](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/71d1d161-b42b-4e47-9922-122319423c40)

**Comment by BethSundberg** [comment]
I give up, it would not upload, I closed the browser tab and started again and it did upload. So there was something odd happening. I will put in an issue if I can figure it out. 

Meanwhile, is there a way to improve the messages from the validator?

**Comment by ielis** [comment]
@belkassaby @BethSundberg this is actually a bug on the validator side and a false positive error. The validator is complaining about missing metadata > resource elements. However, based on created phenopacket, there is no need for a resource element. Thank you for pointing it out, I will fix the validator.

Let's keep this issue open until I update the validator, use it in PhenopacketLab and verify that the input does not raise any errors.

**Comment by BethSundberg** [comment]
This exact scenario does not occur anymore.
