### ISSUE TITLE
When parsing the text mining search, mulitple repeated terms can come up e.g. "Agnosia Observed "

### ISSUE THREAD

**Issue by gerring** [TheJacksonLaboratory/PhenopacketLab#203]
I put in the text below and repeated terms were suggested and added. A given term should appear once. A set should be used on the backend not a list probably. Reproduction of this defect probably does not need this exact text.

"
The unusual combination of symptoms made accurate diagnosis difficult.
She is an expert in the diagnosis and treatment of eye diseases.
The diagnosis was a mild concussion.
His doctor made an initial diagnosis of pneumonia.
The committee published its diagnosis of the problems affecting urban schools.
Recent Examples on the Web
Five years after their diagnosis, 88% of those who took the pill were still alive, compared with 78% of the placebo group.
—Aria Bendix, NBC News, 5 June 2023
David Faustino says Christina Applegate is working on building up her strength amid her multiple sclerosis (MS) diagnosis.
—Abby Stern, Peoplemag, 3 June 2023
Their diagnosis, that Washington is slowly but surely marching toward a direct conflict, might prove correct, but only if Washington follows their advice.
—Michael Mazza And Shay Khatiri, Washington Examiner, 1 June 2023
[See More](javascript:void(0))
These examples are programmatically compiled from various online sources to illustrate current usage of the word 'diagnosis.' Any opinions expressed in the examples do not represent those of Merriam-Webster or its editors. [Send us feedback](https://docs.google.com/forms/d/1GAQr3Kn1cURCVHUA82hAga1Wv8DCH0IuqDLRUrOpN7M/viewform?ts=63f4f653&entry.1515682415=https://www.merriam-webster.com/dictionary/diagnosis) about these examples.

Word History
Etymology
New Latin, from Greek diagnōsis, from diagignōskein to distinguish, from dia- + gignōskein to know — more at [KNOW](https://www.merriam-webster.com/dictionary/know)

First Known Use
1634, in the meaning defined at [sense 1a](https://www.merriam-webster.com/dictionary/diagnosis#h1)

Time Traveler
The first known use of diagnosis was in 1634
[See more words from the same year](https://www.merriam-webster.com/time-traveler/1634?src=defrecirc-timetraveler-etycard)

Phrases Containing diagnosis
[diagnosis related group](https://www.merriam-webster.com/dictionary/diagnosis%20related%20group)
[differential diagnosis](https://www.merriam-webster.com/dictionary/differential%20diagnosis)
"

**Comment by BethSundberg** [comment]
Repeated terms are still suggested. However, they are only added once, which is the desired action
