### ISSUE TITLE
Problem with adding interpretations

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#206]
I want to add two interpretations to the disease heart disorder. 
I put the first one in and clicked Save interpretation.
I added the second row, but when I clicked Save interpretation it told me there already exists an interpretation with the name "new interpretation 10".

---The problem is that I don't need to do a Save at this point, it automatically adds my second row. Only I thought that did not happen because of the message.---------
So I changed the interpretation name to "new interpretation 12".
Then I clicked save interpretation again.

Now I have two identical interpretations that look like this:

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/3dc28aff-0f39-49de-9942-1c1c10e5b58c)

Here is how they look if I open up the accordion. The json also has both sets in it.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/d8562779-447e-493e-bdda-42836d6f9697)

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/75e7f726-63bb-4d9d-a469-6182b202a899)

It makes sense to me that there can be multiple genomic interpretations for one disease, i.e. several rows. 

Does it also make sense to be able to add multiple genomic interpretations for a second disease diagnosis? If yes, then I think the error message needs to convey somehow that I don't need to do a save again for disease diagnosis 1. Also it should clear everything if I decide to add a disease diagnosis 2.

**Comment by belkassaby** [comment]
What about putting the list of created interpretations on the side (the same as for the diseases and phenotypic features, and selecting an interpretation, the user can then edit it by changing the form accordingly?

**Comment by BethSundberg** [comment]
I think this is much easier to use now!!
