### ISSUE TITLE
Spring Auth0 Implementation

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/PhenopacketLab#208]
Enable spring web security and auth0 integration.
Create user domain model and attach these to the phenopacket model.

**Comment by iimpulse** [comment]
#244

**Comment by iimpulse** [comment]
The acceptance criteria is the same for this and the other ticket. Login with and ORCiD account and be able to view your account in the dropdown as well as logout. https://orcid.org/

**Comment by BethSundberg** [comment]
Working on dev
