### ISSUE TITLE
Previous phenopackets are gone after I complete a new one

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#210]
Steps:
Create a phenopacket (title it number 1)
"complete" it
Now it shows up in the listing on the home page
Create another phenopacket (title in number 2)
"complete" it
Now it shows up in the listing on the home page, BUT phenopacket number 1 has vanished

In the screen shot below I tried this a third time, only #3 is listed.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/3e84d4a3-c187-4af9-a36f-11e5f169c1a7)

**Comment by belkassaby** [comment]
Seems to have been fixed 

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/ddb5b2ad-d258-4332-83a7-cf072e0bea68)

**Comment by BethSundberg** [comment]
Confirmed this is fixed.
