### ISSUE TITLE
Confirmation check box enhancement

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#218]
There is a confirmation check box where the user indicates that "I confirm that this ID is not a medical record number, date of birth, initials, location, email, name, address, or any other personal identifying information." The phenopacket cannot be created until the user has checked this box.

HOWEVER, when later editing a saved phenopacket, the user can change the User ID and uncheck the confirmation check box. Should you make sure that the confirmation check box is still checked before saving any changes on the edit individual modal? That would be the one way they might later add personal identifying information to the phenopacket.

**Comment by BethSundberg** [comment]
@belkassaby this feature is not working well. When I first enter a phenopacket, I cannot continue off the individual properties page unless I check the box. However, the error that I have not checked the box is no longer displayed. 

1. I think the error message needs to be added back.

2. If the user goes back to the individual properties page before submitting the phenopacket, this same error message should be displayed if the box is not checked.

3. When clicking OK to leave the edit modal for the individual properties, display the error message again and don't close the modal if the confirmation check box is not checked.

That should fix this problem.

**Comment by belkassaby** [comment]
We were thinking with @ielis to just add this check box once at the last validation step, so it is simpler to manage in the code as well

**Comment by BethSundberg** [comment]
@belkassaby That is a good idea.

**Comment by BethSundberg** [comment]
Working great to have it only once.
