### ISSUE TITLE
Make parent node of modifier tree unselectable

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#225]
## definition of done
the parent nodes in the modifier tree shouldn;t be selectable.

For now we can just keep using the primeng tree select and test if the node is a leaf and set the node selectable property to false otherwise.

Later we should customize a prime ng tree with ng templates and have checkboes only for leaf nodes

**Comment by BethSundberg** [comment]
This applies to diseases and is working as described.
