### ISSUE TITLE
Migrate Files display/Edit UI to primeng 

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#231]

**Comment by BethSundberg** [comment]
@belkassaby the file display looks good. I'm not sure how much of this you expect to be working. I tried adding a URI and the file attributes of key/id are not displayed. I opened this again to show that I had added the key "new field".



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/3e6e5693-fa5b-48d6-b5a2-4583a77f1e6d)

**Comment by BethSundberg** [comment]
@belkassaby I just checked and this works the same way on both dev and sqa sites. Is it working the way you expect?

**Comment by belkassaby** [comment]
@BethSundberg I just committed a fix for this (the label not being correctly displayed) and it should be deployed on dev.

**Comment by BethSundberg** [comment]
Fixed on dev
