### ISSUE TITLE
Make sure the backend returns a sorted list of first 10 terms (on ids)

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#232]
When searching for hypertension, it doesnt come up in the first 10 results provided by the backend as it seems the resuts are not sorted before picking the first 10 and sending it to the frontend.

**Comment by BethSundberg** [comment]
This has been fixed nicely for the phenotypic features search. But the diseases search has not been changed. @belkassaby can you change this also for the diseases search so they work the same?

**Comment by belkassaby** [comment]
It does a sort but it is a sort on the ids: indeed, when I first do the sort, it is on the whole list of features : so If I search for "hypertension" all the names/labels which start with letters before " H" like "Episodic hypertension" will come up in the sorted list before hypertension. WHereas, when i sort by the ids, (HP:1234), the terms with lower ids are usually the simpler ones too. Meaning hypertension will have a lower id than "episodic hypertension".  The main thing here is that in the ten results provided by the backend, we need to show the term that is typed as a possible item selection . The same for the diseases

**Comment by BethSundberg** [comment]
This is working for phenotypic features, so I will close this. I am going to add an enhancement to make the search work this same way for diseases and cause of death.
