### ISSUE TITLE
IDs not saved when I used stepper to go back and enter them

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#236]
I tried creating a phenopacket without entering the phenopacket ID and individual ID. The validator will not let me create a phenopacket until I used the stepper to go back and enter this information. However, the values I entered were not saved.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/2f012a2a-1c80-47ce-bff8-1acce91a3261)

**Comment by BethSundberg** [comment]
If I try to use the validator from the "list" view it gives a new error.


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/f83a7fc7-4dd4-416d-8663-31053dc7097c)

**Comment by BethSundberg** [comment]
@belkassaby The problem gets worse. I created a phenopacket by using the next button. It has saved the two ids properly with no validation errors. But when I go to the list, it is looking odd. The IDs are not showing up and if I validate again I get that error shown above.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/0bb528f6-2429-40ab-8fed-dc1598c11f56)

But the IDs do exist and I can see them if I click on the ID.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/360965c6-390f-4b96-92e3-7c80d4107073)

I think this phenopacket is not listed, it is instead showing something else that is blank? See the turquoise x.


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/974df7e2-43a2-4fb2-bb9f-2ff1633454f6)

**Comment by BethSundberg** [comment]
@belkassaby Here is a clue to what is happening. I tried this on the dev site. I created a phenopacket using the next buttons to get to the last page. It confirmed and saved, showing it fine on the list. Then I clicked on the validator button on the list page. No problems, but when it returned me to the list page, the ID information is gone.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/5885a663-375d-49be-a117-462a168b0be3)

**Comment by BethSundberg** [comment]
Also the delete button is not working. I clicked it and it says it has been deleted, but the list still looks the same.

**Comment by belkassaby** [comment]
After trying a few times, I dont see the first error you pointed out: I can create the phenopacket correctly . 

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/1622f6bb-13a1-4899-b275-d1f9fd0b70d0)
![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/d4dcb99f-a144-48f2-bf36-f7a81de6c482)
![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/60f1020d-b72b-4b79-9b5e-dfdd24410a22)

Then trying to delete the file works fine

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/223a3a0e-5773-4a67-b290-104b80e6cf56)
![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/93c3d74c-764f-4c7c-8fdf-90a9f50a9aa9)

But when trying to validate the file, that's when there is the bug, and then deleting doesnt work anymore too:


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/101e3330-51fe-4667-8d11-3229eca0cd29)
![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/e19ead0e-01c5-4e3f-81f9-d88f8fd9260b)
![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/8bd6ab84-08af-4cbd-a92e-d7b68d3c6cdb)

**Comment by belkassaby** [comment]
For the ID creation, can you try again after having cleaned up your cache? and confirm the bug I found when clicking on the validation button?

**Comment by BethSundberg** [comment]
All of these have been fixed on the Dev site.
