### ISSUE TITLE
change search for diseases and cause of death to work the same as phenotypic features

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#237]
The phenotypic features search has been updated to make sure the term entered shows up in the first 10 terms. The rest of the ten are sorted by ontology ID.

Make the disease search and cause of death search work the same way.

**Comment by belkassaby** [comment]
I m sorting by length first then by alphabetical order : that should fix the issue and agnosia/ hypertension and other searched terms will always come first if by themselves

**Comment by BethSundberg** [comment]
It is working much better now on dev
