### ISSUE TITLE
FAQs documentation missing

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#239]
Documentation needed.. exomiser?

**Comment by pnrobinson** [comment]
The Phenopacket Schema is an emerging GLobal Alliance for Genomics and Health (GA4GH) standard for sharing disease and phenotype information that characterizes an individual person, linking that individual to detailed phenotypic descriptions, genetic information, diagnoses, and treatments.  The Phenopacket Schema, together with other GA4GH data and technical standards, will enable data exchange and provide a foundation for the computational analysis of disease and phenotype information to improve our ability to diagnose and conduct research on all types of disorders, including cancer and rare diseases. Specifically, Phenopackets are designed to be both human and machine‐interpretable, enabling computing operations and validation on the basis of defined relationships between diagnoses, lab measurements, and genotypic information. Phenopackets can be used for a growing number of computational tasks, including serving as input for genomic analysis software such as Exomiser. 

@belkassaby could we add this to the FAQs ?

**Comment by ielis** [comment]
... such as Exomiser, [LIRICAL](https://thejacksonlaboratory.github.io/LIRICAL/stable), [SvAnna](https://svanna.readthedocs.io/en/master)?

@pnrobinson how about a little bit of shameless self-promotion?

**Comment by belkassaby** [comment]
I added Daniel suggestion of links and put some paragraphs so it is more readable.

**Comment by pnrobinson** [comment]
@ielis I would be the last person to experience a sense of shame about self promotion... @belkassaby  -- not sure if the paragraphs about LIRICAL etc were added already?

**Comment by belkassaby** [comment]
@pnrobinson i meant I split the text description you provided into 3 paragraph for more readibility. and added at the end the links to Exomiser, LIRICAL and Svanna. its already deployed on https://phenopacketlab-dev.jax.org/help . let me know if it looks like you expected or if anything needs to be added/changed.
