### ISSUE TITLE
Fix medical action dialog UI

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#240]
The medical action dialog does not yet update itself properly when editing an existing medial action or adding a new medical action.

**Comment by BethSundberg** [comment]
@belkassaby  Editing is working. Adding a medical action to an existing phenopacket is working. 

However, I CANNOT add a medical action to a new phenopacket that I am creating, one that has not been "completed" so it is added to my phenopacket list.

**Comment by belkassaby** [comment]
through the stepper the medical action is not working? let me check and fix this.

**Comment by belkassaby** [comment]
See #288

**Comment by BethSundberg** [comment]
Fixed
