### ISSUE TITLE
Adding phenotypic feature(s) to an existing phenotype wipes some previously added ones

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#245]
On the dev site

I used text mining to create 3 phenotypic features.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/f0237bd5-ff7c-4343-a333-1f7eb57939d5)

Click on add phenotypic feature to add more

Create pneumonia and add it

One of the previously added features is gone. It looks like only a maximum of 3 are displayed?

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/6742d3a0-41f9-4ed0-9686-0d198e9494e8)

**Comment by belkassaby** [comment]
fix deployed in Dev

**Comment by BethSundberg** [comment]
Tested on dev and is fixed
