### ISSUE TITLE
Adding an interpretation to a list of empty interpretations does not add it

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#249]
For a phenopacket without any interpretations, adding an interpretation does not add it. If the phenopacket has already some interpretations, the new interpretation is correctly added.

**Comment by BethSundberg** [comment]
@belkassaby Have you deployed this to dev yet? Because it is not working.

**Comment by BethSundberg** [comment]
This is now working on dev
