### ISSUE TITLE
Sidebar buttons not working

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#256]
On the dev site, When I am looking at a phenotype, the sidebar buttons (both) don't do anything.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/8e70dd1c-7106-452d-bb5c-733de4dd6029)

If I am looking at a list of phenotypes, the "+Add phenotype" button does not do anything.

If I start up the browser, the "+Add Phenotype" button does not do anything

**Comment by BethSundberg** [comment]
@belkassaby The +Add Phenotype button is working now on dev.

However, when the screen is showing some phenopackets (see screen shot) the sidebar "Phenopackets" does not return the list. To get to the list you must click on the "phenopackets" link on the main screen. If you are creating a phenopacket that is not yet completed, then the "phenopackets" on the sidebar returns the list. Is this desired? I thought before the sidebar button always returned the list.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/75ba1c57-720d-42c7-b86a-f992ea7a35ac)

**Comment by iimpulse** [comment]
Theres not much use currently for the sidebar. I am in favor of removing it for now.

**Comment by belkassaby** [comment]
I will remove in this PR https://github.com/TheJacksonLaboratory/PhenopacketLab/pull/254 before merging yeah?

**Comment by BethSundberg** [comment]
This problem is solved on dev by removing the sidebar
