### ISSUE TITLE
Add Schedule frequency NCIT endpoint

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#259]
## Definition of done
Add Schedule frequency NCIT endpoint that returns the https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C64493 and children NCIT terms as SubTreeNode

**Comment by BethSundberg** [comment]
@belkassaby Where will this be used, I don't see something that asks for it.

**Comment by belkassaby** [comment]
This should be in Treatment, Dose interval , then the schedule frquency should be callable

**Comment by BethSundberg** [comment]
@belkassaby I found under treatment "cumulative dose" that has null objects. I don't see dose interval.


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/82e07630-354b-4c66-9f24-c5da59adcfeb)

**Comment by BethSundberg** [comment]
@belkassaby If I upload a phenotype that has a medical action, I can see this.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/13b4b7ae-4465-42d6-8f07-3fe776df8cba)

**Comment by BethSundberg** [comment]
Okay, so the schedule frequency is there. However, the form itself needs to be fixed, which is a separate issue.
