### ISSUE TITLE
Add Adverse event endpoint with NCIT terms

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#260]
## Definition of done
Add Adverse event endpoint that return A subTreeNodes of NCIT terms for "adverse events" https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C41331

**Comment by BethSundberg** [comment]
These are visible on dev

**Comment by BethSundberg** [comment]
The OAE terms are available
