### ISSUE TITLE
Phenopacket Persistence

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/PhenopacketLab#263]
As a user I would like the ability to save my phenopackets and return to them at a later time. I would like to be able to update/delete.

**Comment by BethSundberg** [comment]
@iimpulse How would I save? I don't see them if I close the browse window and later log on again.

**Comment by BethSundberg** [comment]
This looks great. I tried two different browsers open at the same time and any changes show up after doing a browser refresh.
