### ISSUE TITLE
Add endpoint for body site

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#264]
## definition of done
add an endpoint that returns all the body region part of the body region node of the NCIT ontology : https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C12680&lang=en&viewMode=All&siblings=false

**Comment by BethSundberg** [comment]
@belkassaby 
Attempt to create a medical action
There is a body site drop-down on the page after setting the Action type to "procedure"
It is not finding anything from the ontology. There is a body type drop-down when the action type is "radiation therapy" and it is also not finding anything from the ontology.


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/0b1c0248-acbd-4737-a694-77248bde52ad)



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/8c791573-859f-4b30-8833-97de4969aedf)

**Comment by belkassaby** [comment]
This has just been deployed on dev
