### ISSUE TITLE
Add endpoint for procedure

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#265]
## definition of done
add endpoint for procedures that will return all nodes children of the maxo node 'diagnostic procedure' https://www.ebi.ac.uk/ols/ontologies/maxo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMAXO_0000003&lang=en&viewMode=All&siblings=false

**Comment by BethSundberg** [comment]
@belkassaby Where is this node used? 


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/9b9cf834-f11b-4916-96c8-87039e58ea57)

I find these NCIT terms



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/3d7167ab-55f5-459f-8d97-1730a9f935dc)

**Comment by belkassaby** [comment]
@BethSundberg yest that's the procedure codes
