### ISSUE TITLE
Add endpoint for radiation therapy

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#266]
Add endpoint that will return all children nodes of the 'radiation therapy ' maxo term : https://www.ebi.ac.uk/ols/ontologies/maxo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMAXO_0000014&lang=en&viewMode=All&siblings=false

**Comment by BethSundberg** [comment]
@belkassaby I am confused about how the endpoint works. The link you have is to only a short list, which I don't see anywhere to choose:


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/4ff6b5cf-f68a-4407-8d25-d0a5f08e6551)

But I have lots of choices for radiation therapy modality from a different ontology:



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/5d10753a-13ae-4cc0-99a7-7c97c97c1a27)

**Comment by belkassaby** [comment]
@BethSundberg it's the radiationtherapy modality
