### ISSUE TITLE
Add unit endpoint  using uo ontology

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#268]
## definition of done
add unit endpoint and frontend corresponding methods

**Comment by BethSundberg** [comment]
@belkassaby When I upload an existing phenopacket, I can see that this endpoint has been added. I cannot see it when creating a new phenopacket so the UI still needs work.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/25d4b791-c06a-4a1c-bae5-b82eab970c38)

Also note if I save a value, it gives me an object error on the main page.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/d65883ba-2339-45b4-ae1e-843b61776e03)

**Comment by BethSundberg** [comment]
@belkassaby I am still getting an error when I try to add a treatment.


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/d9945d30-fb4b-4193-82c7-1d6a957ad66d)

**Comment by BethSundberg** [comment]
The unit endpoint exists and I can edit an existing treatment
