### ISSUE TITLE
Gestational age | days can be set to >= 7 days

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#273]
The days sub-field of Gestational age can be set to >= 7 days. However, the values must be in range `0..6` (inclusive).

![image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/12170955/e44feea3-9a05-4c65-b9d9-e2c1e49940ff)

**Comment by BethSundberg** [comment]
Fixed

**Comment by ielis** [comment]
I can still set days to 31 while it should be allow to set it to an int in range 0, 6 (inclusive) or None. Did the fix make it into SQA instance?

**Comment by C-1337ka** [comment]
0-6 Inclusive

**Comment by BethSundberg** [comment]
fixed
