### ISSUE TITLE
Metadata fixes are not saved

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#275]
I uploaded a phenopacket that does not have the metadata in it. The validator points this out and offers to fix that issue. However, the fixes are not saved. Is that okay or should they be saved?

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/06763f2c-1b6a-4e0b-ba43-5e556d1558d6)

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/83aea745-628a-4163-b0d8-74d44bca09b0)

**Comment by BethSundberg** [comment]
See issue 277, it is the same error. There are more screen shots there.

**Comment by BethSundberg** [comment]
Once I closed the browser and reopened, SOME of the metadata was saved. It went from 34 errors to 9. This is using bethlem-myopathy example.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/f34807ae-5944-41e5-b1ca-60805ae20d3b)

It looks like all were saved, but some are not.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/edf1cc2f-d7c3-4953-a8d4-3386b0ec2329)

**Comment by belkassaby** [comment]
Fixing #280 has fixed this issue too

**Comment by BethSundberg** [comment]
SQA confirms that this is fixed.
