### ISSUE TITLE
Medical Actions treatment termination window is off screen

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#283]
I cannot see the top of the treatment termination choices. Also, does it have a search feature?

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/5a4cafa1-4cd1-4c62-b237-d1f96cfe6255)

**Comment by belkassaby** [comment]
This behaviour is normally automatic, given the screen size and where the dropdown is located on window. If more space in the bottom it should display in the bottom. Try moving the whole dialog up, then select the dropdown again. it should display at the bottom. Here in this example it is about in the middle of your screen.

**Comment by BethSundberg** [comment]
@belkassaby It is looking better now, all is fitting.
