### ISSUE TITLE
Typography since material deprecation

### ISSUE THREAD

**Issue by iimpulse** [TheJacksonLaboratory/PhenopacketLab#284]
We would like to include new typography for prime

**Comment by belkassaby** [comment]
Commit 37dcc02dcd4a9a95a920265096ae903873b4bf11 should have solved this?

**Comment by BethSundberg** [comment]
@iimpulse  Please see ticket 285, where I listed places with obvious text differences. The text now seems to be smaller than on SQA. You can decide if you approve.
