### ISSUE TITLE
Creator session persistence

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#291]
1. I start creating a phenopacket in the creator/stepper. 
2. I cancel from whatever reason by clicking the phenopacket icon on the upper left side.
3. I start the creator again to create a new phenopacket. 

### Issue

I see the content from the previous session and I have to manually clear the fields. This is undesirable - a laborious task where the user may inadvertently add data from the previous attempt.

### DOD

The stepper starts with a fresh session upon each run.

**Comment by BethSundberg** [comment]
Fixed
