### ISSUE TITLE
Null value in a non-null field

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#292]
1. Open the creator
2. Start setting the age
   - select gestational age
   - type `9` to weeks
   - type `6` to days
   - delete 6 (change my mind, I actually do not know what to put here, so I'm leaving it blank)
     > I expect this sets the text field to an empty string or `null`, and marks the field as "tampered with"
3. Go to *Validate* section and hit complete

### Issue

I get the following:

![image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/12170955/2cfc2cdf-7ec9-4744-b831-c4e8b7149078)

The validator in the backend correctly points out the issue - an `int` field is `null`. The corresponding (errorneous) phenopacket would look like:

```
{
  "id": "whatever-phenopacket-id",
   "subject": {
      "taxonomy": {
         "id": "NCBITaxon:9606",
         "label": "Homo sapiens"
      },
      "id": "jimmy",
      "timeAtLastEncounter": {
         "gestationalAge": {
            "weeks": 9,
            "days": null
         }
      }
   },
  ...
```
> Note the `null` in `subject > timeAtLastEncounter > gestationalAge > days`

The issue can be "fixed" if the user types a value into the field. However, this is undesirable because gestational age of e.g. `P22W` and `P22W0D` have different interpretation.

### DOD

Clearing optional field won't result in a null field.

*Note* - this likely applies to other fields as well. See #293 for a similar issue

**Comment by BethSundberg** [comment]
Looks fine
