### ISSUE TITLE
Clearing field produces an invalid value

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#293]
1. Start creating phenopacket with stepper/creator
2. Add required individual fields (unrelated to the issue but to make the code work)
3. Select `Age` from the dropdown, in order to add individual's age.
4. Clear `Age` by clicking on the cross in the dropdown
5. Proceed to validate, confirm absence of personal info, and click *Complete*

### Issue

The validator correctly points out presence of errors:

![image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/12170955/6a6ec917-922d-4b4e-a5b3-7260417b1754)

The errors are unfixable unless the user adds age despite not wanting to. Of course, he must also know that.

This is likely caused by sending a phenopacket with a phenopacket with empty object instead of valid `timeAtLastEncounter` value:

```json
..
"subject": {
   "id": "jimmy",
   "taxonomy": {
      "id": "NCBITaxon:9606",
      "label": "Homo sapiens"
   },      
   "timeAtLastEncounter": {}
}
..
```
> Note  `"timeAtLastEncounter": {}`

However, `{}` is *not* a valid value of the field.

### DOD

Clearing an optional field won't leave an empty object in place.

**Comment by BethSundberg** [comment]
Fixed, checked this with several other fields and no problems
