### ISSUE TITLE
Therapeutic Regimen Error 

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#302]
Therapeutic regimen UI allows the saving of corrupt phenopackets that then will block the reloading of the previously created phenopaket 
![image001](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/ee69353b-9b8d-429a-810f-a327e93a35fe)

**Comment by BethSundberg** [comment]
@belkassaby I did not have this error occur on dev.

**Comment by belkassaby** [comment]
This might be due to a corrupt phenopacket that you had previously created on sqa (the old instance)
i would clear up all you phenopackets in sqa and then you could try once more to see if that happens on sqa

**Comment by BethSundberg** [comment]
@belkassaby Logoff and login are working fine on both dev and sqa sites this morning. Problem is solved.
