### ISSUE TITLE
confirmation dialog for features and diseases displayed behind the edit dialog

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#304]
When searching for diseases or features sometimes the confirmation dialog pops up behind the search edit dialog
![Screenshot 2023-08-30 at 4 55 04 PM](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/d9f13890-5bb1-4d52-9ded-bd86dd7a95ae)

**Comment by desais-jax** [comment]
tested
