### ISSUE TITLE
Back button does not work if toggle from all to rare stepper

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#305]
Start to create a phenotype
fill in the individual page
Change stepper from rare to all 
go to file step
add a file
change stepper from all to rare
The file information is still shown, with only one button, the "back" button
Click the back button
Nothing happens on the UI
It causes this console error

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/dd112eb9-aff6-4866-bb11-564ed17ae13f)

It is possible to continue working by using the stepper to move to a different step

**Comment by desais-jax** [comment]
@belkassaby I followed the steps above, I did not see error in console button but when I clicked back button after switching to Rare disease steps , I got the File step 


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/72874793/f9d57f03-2cb8-43c3-957b-5113ab6f886d)
