### ISSUE TITLE
Interpretations not saving Alternate IDs, Xrefs, Alternate symbols

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#306]
Create a phenopacket and submit it.
From the phenopacket list, open this phenopacket
Add an interpretation. Fill in every field. At the very end, add an Alternate ID, an Xref, an alternate symbol.
Save/add the interpretation
Use the edit feature to go back into this interpretation.
These three fields are not displayed, I think they were possibly not saved.

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/4a86ad68-5243-4b87-ba44-55ff138c0bb7)

They are also not shown on the phenopacket list when it is opened to display the interpretation

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/87c81bcb-0ed0-4c00-be43-57364e396984)

The structural type value was also not saved

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/a0019845-ef96-47a5-b8d5-f9f8fe448630)

I put "testing" into the Ref Allele Sequence field. It did save this, but does not display it on the phenotype list screen, perhaps because this string does not make sense? See earlier screen shot.

**Comment by BethSundberg** [comment]
@belkassaby 
Ref Allele Sequence field is working now.
The three fields, Alternate ID, Xref, and alternate symbol are not displayed when the phenopacket list is shown, but that is okay if it is how you want it to work.

The PROBLEM is that I cannot enter an Alternate ID. It says it will validate it. I tried repeating values already shown or altering them slightly. These are not saved. Is it because they are duplicates or not valid? There is no error message. This example comes from uploading bethlem-myopathy-phenopacket from the example files.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/3b32a9ed-3441-463b-97fc-4c7ce12393e8)

I also tried creating a new interpretation for a phenopacket I created. On this screen the + icons do not work for any of the three fields: Alternate ID, Xref, and Alternate symbol. If you don't want to allow adding??? can you remove the + icons.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/9e64f8f7-07bb-40d9-b51c-ee3732660630)

**Comment by BethSundberg** [comment]
@belkassaby See Peter's comment on issue 159. Should adding/editing not be allowed here?

**Comment by belkassaby** [comment]
You should now be able to save alternate ids, xrefs and alternate symbols. (I removed this UI for genedescriptor in the stepper). But in the edit UI, we should be able to edit as much as possible, as it is supposed to be a more expert way of editing phenopackets, rather than through the phenopackets. Also, not implemented yet is the id and symbol of the gene, which here are simple input field. They will eventually be replaced by a list of all existing/known human genes with corresponding hgnc id and symbol. See ticket #33

**Comment by BethSundberg** [comment]
@belkassaby It is now saving the Alternate IDs and Xrefs. However, the + icon for Alternate symbol is not working.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/fa35dd6e-18db-4b0d-9a75-d27780556e97)

**Comment by belkassaby** [comment]
Ha I had `[(ngModel])` instead of `[(ngModel)]` ....

**Comment by BethSundberg** [comment]
Fixed
