### ISSUE TITLE
Evidence endpoint

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/PhenopacketLab#37]
Supply values for `PhenotypicFeature | Evidence`.

**Comment by ielis** [comment]
@pnrobinson 
We should provide evidence codes for `PhenotypicFeature | Evidence` and I'm wondering which codes these should be exactly. It seems like _EFO_ concepts are a good fit for the evidence concepts, but I do not want to just bluntly offer all the concepts in the UI. We should make it simpler for the user by offering a list of pre-selected evidence codes.

The first candidates are `PCS`, `TAS`, and `IEA`, as used in HPOA. I assume these correspond to certain _EFO_ concepts, however, I'm not sure which ones. Do you know which (if any) _EFO_  concepts correspond to `PCS`, `TAS`, and `IEA`?

Should we include any other _EFO_ concepts on top of the three above?

**Comment by pnrobinson** [comment]
I agree we should offer a limited number of codes as a choice-box widget (and possible allow users to enter custom codes if they must). The three HPO codes map 1:1 to ECO codes and probably we should use ECO codes for external users. We should ask Chris and Melissa and Jules about ideas for what codes we want to offer

**Comment by BethSundberg** [comment]
The evidence codes are listed in the more details section.
