### ISSUE TITLE
Refactor Frontend theming

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#56]
Remove the material-dashboard theming dependency and only rely on the angular material and custom theming. This will remove a lot of potential styles overlap and remove all the existing warnings that come up in the log.

## Definition of done
material-dashboard dependency is removed and replaced by a custom angular material similar to mpd-ui

**Comment by iimpulse** [comment]
rev angular https://update.angular.io/
