### ISSUE TITLE
Use API endpoints to populate all the corresponding UIs

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#58]
Use the API endpoints associated with all their corresponding ontologies to populate the UIs

## Definition of done
When the fakebackend can be turned off and replaced by the backend with the same results to the UI.

**Comment by C-1337ka** [comment]
Test: Beth to create a Phenopacket with every object (can also expand on the pre-existing full Phenopacket)

**Comment by BethSundberg** [comment]
I have used as many objects as possible. Any issues will be discussed later. These basically look good.
