### ISSUE TITLE
implement a tree search UI on modifiers and other OntologyClasses

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#84]
## Definition of done
implement using the available https://www.primefaces.org/primeng/treeselect tree select component to search through modifiers, and other ontology classes terms.

**Comment by ielis** [comment]
Hi @belkassaby the trees look great. I think one last missing item to make it perfect is to remove the top-level tree elements. 

- for _Onset_, we should not show the top-level `Onset` term, but only the children: `Adult onset`, `Antenatal onset`, etc.
- for _Modifiers_, we should not show the top-level `Clinical modifier`, but only the children: `Clinical course`, `Position`, etc.

**Comment by belkassaby** [comment]
linked to PR #81
