### ISSUE TITLE
Time of last encounter

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#87]
The data type for time of last encounter needs to be a selection of

1. TimeElement.Age
2. TimeElement.GestationalAge
3. TimeElement.AgeRange

(right now, only the first option is available).

**Comment by pnrobinson** [comment]
Time of death in VitalStatus should be the same as the above.

**Comment by pnrobinson** [comment]
Cause of death -- should be provided by backend. For now, please load a few example terms from Mondo (this should be an OntologyClass representing a disease, e.g., [diabetes mellitus, noninsulin-dependent, 3](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011363)

**Comment by ielis** [comment]
@belkassaby the time of last encounter offers 4 options instead of the 3 options requested above. Can you please remove the ontology class?

**Comment by ielis** [comment]
@belkassaby the same applies to Time of death. Please remove the ontology class option from the combo box menu.
