### ISSUE TITLE
Vital status / Cause of death

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#88]
Cause of death -- should be provided by backend. For now, please load a few example terms from Mondo (this should be an OntologyClass representing a disease, e.g., [diabetes mellitus, noninsulin-dependent, 3](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011363)

**Comment by ielis** [comment]
We have a shortlist of Mondo diseases in the Cause of death UI now. The full list will be provided by a backend endpoint (TODO).
