### ISSUE TITLE
Migrate application to PrimeNG

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#94]
All angular material components should be migrated to primeng.

- [x] Main Content - Sidebar - Nav #123 
- [x] PhenopacketList #110 
- [x] All material tables in phenopacket component
- [x] Material Dialogs

**Comment by C-1337ka** [comment]
Need to do:

1. Individual description in a phenopacket - expandable/widget - still in Angular
2. Angular material tables; 
3. Summary table
4. Phenopacket table

**Comment by BethSundberg** [comment]
All of these elements look good.
