### ISSUE TITLE
Add a pre-stepper selection page to select the type of creator

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#97]
## Definition of done
After clicking on "create a new phenopacket" the user should be able to select the type of phenopacket creation they want from "all steps available" to "rare disease phenotypic profile" which would show just a few (individual, phenoptypic feature, disease) steps in the phenopacket creation stepper.

**Comment by belkassaby** [comment]
@ielis beside the profiles above, what other profiles should we show? consisting of what step for each profile?

**Comment by ielis** [comment]
@belkassaby I don't know that yet. I know what is useful in the rare disease setting, but regarding the other areas/profiles, we need to gather requirements from the collaborators after we have a working prototype. So, for now, let's create just 2 profiles: rare disease and full. We will add the other profiles later.
